[settings]
python.uv_venv_auto = true
python.default_packages_file = "~/.default-python-packages"
idiomatic_version_file_enable_tools = ["python", "node"]
disable_backends = [ "pipx" ]
experimental = true

[tools]
chezmoi = "latest"
golang = "latest"
python = "latest"
uv = "latest"
rust = "stable"
node = "lts"
bun = "latest"
lua-language-server = "latest"
zls = "latest"
zig = "latest"
shellcheck = "latest"
shfmt = "latest"
usage = "latest"
jq = "latest"
qsv = "latest"
gh = "latest"

# system tools
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:ClementTsang/bottom" = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:starship/starship" = "latest"
"aqua:JohnnyMorganz/StyLua" = "latest"
"aqua:dandavison/delta" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:ducaale/xh" = "latest"
"aqua:tree-sitter/tree-sitter" = "latest"
"cargo:xan" = "latest"
rclone = "latest"
"aqua:aws/aws-cli" = "latest"
1password = "latest"
claude = { version = "latest", bin = "claude", platforms = """
[linux-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/linux-arm64/claude"

[linux-x64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/linux-x64/claude"

[macos-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/darwin-arm64/claude"

[macos-x64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/darwin-x64/claude"
""", version_list_url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/stable" }
task = "latest"
