add_newline = false

[aws]
disabled = true

[gcloud]
disabled = true

[ruby]
symbol = "ğŸ’"
disabled = false

[python]
symbol	= "ğŸ"
disabled = false

[rust]
symbol = "ğŸ¦€"
disabled = false

[kubernetes]
style = "dimmed green"
disabled = false

[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "k3s"

[conda]
disabled = true
